name: release

on:
  push:
    branches: [ main ]

jobs:
  version:
    runs-on: ubuntu-latest
    container:
      image: codacy/git-version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fix tar access
        run: apk add --update --no-progress tar
      - name: Fix git access
        run: |
          git config --global --add safe.directory '*'
      - name: Get next version
        id: version
        run: |
          export NEXT_VERSION="$(/bin/git-version --folder=$PWD --release-branch=main)"
          echo "Next version is ${NEXT_VERSION}"
          echo "version=${NEXT_VERSION}" >> $GITHUB_ENV
          echo "version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.version.outputs.version }}

  build:
    runs-on: ubuntu-latest
    needs: [ version ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs

      - name: Test
        run: ./gradlew test

      - name: Test
        run: ./gradlew publish -Pversion=${{ needs.version.outputs.version }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag:
    runs-on: ubuntu-latest
    needs: [ version, build ]
    steps:
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ needs.version.outputs.version }}"
